#!/usr/bin/env node
// "Fast AND faithful?" — the one chart that combines this project's two unique
// gateway measurements: independently-measured overhead (x, lower is better) and
// protocol-fidelity score (y, higher is better). No other benchmark plots both,
// because no other benchmark measures both. One dot per gateway we've measured on
// BOTH axes; the top-left quadrant (low latency + full fidelity) is the sweet spot.
//
// Pure `buildScatterSvg()` is unit-tested; the CLI reads data/overhead.json +
// data/fidelity.json and writes web/fidelity-scatter.svg (regenerated by
// aggregate.mjs so it tracks the live CI numbers). Dependency-free SVG — crisp on
// GitHub Pages, no plotting library, no PNG raster step.

import { readFile, writeFile } from 'node:fs/promises';

const esc = (s) => String(s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

/** Join overhead + fidelity by gateway name; keep only gateways present on BOTH. */
export function joinMetrics(overhead, fidelity) {
  const fByName = new Map((fidelity ?? []).map((e) => [e.name, e]));
  const out = [];
  for (const o of overhead ?? []) {
    const f = fByName.get(o.name);
    const ms = o?.verdict?.overhead_ms;
    // passed = count of the three passthrough checks that passed (0..3)
    const passed = f?.verdict ? [f.verdict.tool_calls, f.verdict.streaming, f.verdict.stream_usage].filter(Boolean).length : null;
    if (typeof ms === 'number' && typeof passed === 'number') {
      out.push({ name: o.name, version: o.version ?? f?.version ?? '', overhead_ms: ms, score: passed });
    }
  }
  return out.sort((a, b) => a.overhead_ms - b.overhead_ms);
}

/** Build a self-contained SVG scatter (overhead x, fidelity y). Pure + deterministic. */
export function buildScatterSvg(points, opts = {}) {
  const W = 680, H = 440;
  const m = { l: 76, r: 150, t: 58, b: 64 };
  const plotW = W - m.l - m.r, plotH = H - m.t - m.b;
  const x0 = m.l, y0 = H - m.b; // origin (bottom-left of plot)
  const xmax = Math.max(6.5, Math.ceil((Math.max(0, ...points.map((p) => p.overhead_ms)) * 1.18) / 0.5) * 0.5);
  const ymax = 3;
  const px = (ms) => x0 + (ms / xmax) * plotW;
  const py = (score) => y0 - (score / ymax) * plotH;
  const color = (s) => (s >= 3 ? '#3fb950' : s >= 2 ? '#d29922' : '#f85149');

  const parts = [];
  parts.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="-apple-system,Segoe UI,Roboto,sans-serif" role="img" aria-label="Gateways plotted by measured overhead versus protocol fidelity">`);
  parts.push(`<rect width="${W}" height="${H}" fill="#0d1117"/>`);
  // sweet-spot quadrant (low overhead, full fidelity) — top-left. Label sits at
  // the BOTTOM-left of the shaded band so it never collides with a point up top.
  const sweetX = px(xmax * 0.42);
  const sweetBottom = py(2.5);
  parts.push(`<rect x="${x0}" y="${m.t}" width="${sweetX - x0}" height="${sweetBottom - m.t}" fill="#3fb950" opacity="0.07"/>`);
  parts.push(`<text x="${x0 + 8}" y="${sweetBottom - 8}" fill="#3fb950" font-size="11" opacity="0.9">◤ fast &amp; faithful zone</text>`);
  // title + subtitle
  parts.push(`<text x="${x0}" y="30" fill="#e6edf3" font-size="16" font-weight="700">Fast <tspan fill="#8b949e">AND</tspan> faithful? Gateways by measured overhead × fidelity</text>`);
  parts.push(`<text x="${x0}" y="47" fill="#8b949e" font-size="11.5">Both axes independently measured on a neutral CI runner — no keys, reproducible. ${esc(opts.asOf ? '· ' + opts.asOf : '')}</text>`);
  // axes
  parts.push(`<line x1="${x0}" y1="${m.t}" x2="${x0}" y2="${y0}" stroke="#30363d" stroke-width="1"/>`);
  parts.push(`<line x1="${x0}" y1="${y0}" x2="${x0 + plotW}" y2="${y0}" stroke="#30363d" stroke-width="1"/>`);
  // y ticks (0..3) + gridlines
  for (let s = 0; s <= 3; s++) {
    const y = py(s);
    parts.push(`<line x1="${x0}" y1="${y}" x2="${x0 + plotW}" y2="${y}" stroke="#21262d" stroke-width="1"/>`);
    parts.push(`<text x="${x0 - 10}" y="${y + 4}" fill="#8b949e" font-size="11" text-anchor="end">${s}/3</text>`);
  }
  // x ticks (even ms)
  for (let t = 0; t <= xmax + 0.01; t += 2) {
    const x = px(t);
    parts.push(`<line x1="${x}" y1="${y0}" x2="${x}" y2="${y0 + 5}" stroke="#30363d" stroke-width="1"/>`);
    parts.push(`<text x="${x}" y="${y0 + 19}" fill="#8b949e" font-size="11" text-anchor="middle">${t}</text>`);
  }
  // axis labels
  parts.push(`<text x="${x0 + plotW / 2}" y="${H - 14}" fill="#c9d1d9" font-size="12" text-anchor="middle">Added latency per request (ms) — lower is better →</text>`);
  parts.push(`<text transform="translate(20 ${m.t + plotH / 2}) rotate(-90)" fill="#c9d1d9" font-size="12" text-anchor="middle">Protocol fidelity (checks passed) — higher is better</text>`);
  // points + labels
  for (const p of points) {
    const cx = px(p.overhead_ms), cy = py(p.score);
    parts.push(`<circle cx="${cx.toFixed(1)}" cy="${cy.toFixed(1)}" r="7" fill="${color(p.score)}" stroke="#0d1117" stroke-width="1.5"/>`);
    const label = `${esc(p.name)}`;
    const sub = `${p.overhead_ms.toFixed(2)} ms · ${p.score}/3`;
    // place label to the right, unless too close to right edge then left
    const right = cx < x0 + plotW - 96;
    const lx = right ? cx + 12 : cx - 12;
    const anchor = right ? 'start' : 'end';
    parts.push(`<text x="${lx.toFixed(1)}" y="${(cy - 2).toFixed(1)}" fill="#e6edf3" font-size="12.5" font-weight="600" text-anchor="${anchor}">${label}</text>`);
    parts.push(`<text x="${lx.toFixed(1)}" y="${(cy + 13).toFixed(1)}" fill="#8b949e" font-size="10.5" text-anchor="${anchor}">${esc(sub)}</text>`);
  }
  parts.push(`</svg>`);
  return parts.join('\n');
}

// ---------- CLI ----------

async function main() {
  const root = new URL('../', import.meta.url);
  const rd = async (p) => { try { return JSON.parse(await readFile(new URL(p, root), 'utf8')); } catch { return null; } };
  const overhead = (await rd('data/overhead.json'))?.results ?? [];
  const fidelity = (await rd('data/fidelity.json'))?.results ?? [];
  const points = joinMetrics(overhead, fidelity);
  if (!points.length) { console.error('[scatter] no gateways with both overhead + fidelity; skipping'); return; }
  const asOf = new Date().toISOString().slice(0, 10);
  const svg = buildScatterSvg(points, { asOf });
  const out = new URL('web/fidelity-scatter.svg', root);
  if (process.argv.includes('--check')) {
    const cur = await readFile(out, 'utf8').catch(() => '');
    // ignore the as-of date line when drift-checking (it changes daily)
    const strip = (s) => s.replace(/neutral CI runner[^<]*/g, 'neutral CI runner');
    if (strip(cur) !== strip(svg)) { console.error('[scatter] web/fidelity-scatter.svg is stale — run node probe/make_scatter.mjs'); process.exit(1); }
    console.log('[scatter] up to date'); return;
  }
  await writeFile(out, svg);
  console.log(`[scatter] web/fidelity-scatter.svg: ${points.length} gateways (${points.map((p) => p.name).join(', ')})`);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
